[package]
name = "create_pool"
version = "0.1.2"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
ekubo = { git = "https://github.com/ekuboprotocol/abis" }
sncast_std = "0.40.0"
starknet = ">=2.11.2"

[dev-dependencies]
cairo_test = "2.11.2"
